dist: trusty
os: linux
language: c

env:
  global:
    - PREFIX=${HOME}/opt
    - PATH=${PREFIX}/bin:${PATH}
    - LD_LIBRARY_PATH=${PREFIX}/lib:$LD_LIBRARY_PATH
    - OPENSSL_BRANCH=OpenSSL_1_1_1-stable

addons:
  apt:
    update: true
    
matrix:
  include:
    - name: linux/gcc/x86_64
      os: linux
      compiler: gcc
    - name: linux/gcc/ppc64le
      os: linux
      arch: ppc64le
      compiler: gcc
    - name: linux/gcc(ASan)/x86_64
      env: SAN=-DASAN=1
      os: linux
      compiler: gcc
    - name: linux/gcc+Coverity/x86_64 (cron)
      env: COVERITY_SCAN_PROJECT_NAME="gost-engine" COVERITY_SCAN_BRANCH_PATTERN="*" COVERITY_SCAN_NOTIFICATION_EMAIL="beldmit@gmail.com" COVERITY_SCAN_BUILD_COMMAND="make"
      if: type == cron
      os: linux
      compiler: gcc
      script:
        - mkdir build
        - cd build
        - cmake -DOPENSSL_ROOT_DIR=${PREFIX} -DOPENSSL_LIBRARIES=${PREFIX}/lib -DOPENSSL_ENGINES_DIR=${PREFIX}/engines ..
        - curl -s "https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh" | bash || true
    - name: linux/gcc/arm64
      os: linux
      arch: arm64
      compiler: gcc
      env:  SAN=-DTSAN=1
    - name: linux/clang/arm64
      os: linux
      arch: arm64
      compiler: clang
      env:  SAN=-DTSAN=1
      addons:
        apt:
          packages:
            - clang-6.0
    - name: osx/clang/x86_64
      os: osx
      compiler: clang

before_install:
  - if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get -y install cmake;  fi
  
before_script:
  - curl -L https://cpanmin.us | sudo perl - --sudo App::cpanminus
  - sudo cpanm --notest Test2::V0 > build.log 2>&1 || (cat build.log && exit 1)
  - git clone --depth 1 -b ${OPENSSL_BRANCH} https://github.com/openssl/openssl.git
  - cd openssl
  - ./config shared -d --prefix=${PREFIX} --openssldir=${PREFIX} && travis_wait make -s -j$(nproc) all && make -s install_sw
  - cd ..

script: 
  - mkdir build
  - cd build
  - cmake -DOPENSSL_ROOT_DIR=${PREFIX} -DOPENSSL_LIBRARIES=${PREFIX}/lib -DOPENSSL_ENGINES_DIR=${PREFIX}/engines ${SAN} ..
  - make
  - if [ -n "$SAN" ]; then
       find .. -type f -name *.c -exec ./bin/gost1sum -v {} \; > .check;
       ./bin/gost1sum -vc .check;
    fi
  - make test CTEST_OUTPUT_ON_FAILURE=1